[package]
name = "tokel-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
tokel-engine = { version = "0.1.0", path = "../tokel-engine" }

[dependencies.quote]
version = "1.0"

[dependencies.proc-macro2]
version = "1.0"

[dependencies.syn]
version = "2.0"
features = ["clone-impls", "parsing", "extra-traits"]
