[package]
name = "tokel-derive"
description = "Procedural macro entry points and derive implementations for the Tokel templating engine."
keywords = ["parsing", "ast", "evaluation", "metaprogramming", "tokel"]
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]
readme = "README.md"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tokel-engine.workspace = true
tokel-std.workspace = true
