[package]
name = "tokel-derive"
description = "Procedural macro entry points and derive implementations for the Tokel templating engine."
keywords = ["parsing", "ast", "evaluation", "metaprogramming", "tokel"]
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]
readme = "README.md"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
tokel-engine = { version = "0.2.4", path = "../tokel-engine" }
tokel-std = { version = "0.2.4", path = "../tokel-std" }

[dependencies.quote]
version = "1.0"

[dependencies.proc-macro2]
version = "1.0"

[dependencies.syn]
version = "2.0"
features = ["clone-impls", "parsing", "extra-traits"]
