[package]
name = "tokel"
description = "A declarative, pipeline-based templating engine for simplifying Rust procedural macros."
keywords = ["proc-macro", "macro", "metaprogramming", "templating", "tokenstream"]
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]
readme = "README.md"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokel-derive = { workspace = true, optional = true }
tokel-engine = { workspace = true, optional = true }

[dev-dependencies]
trybuild.workspace = true

[features]
default = ["derive"]

derive = ["dep:tokel-derive"]
engine = ["dep:tokel-engine"]
