[package]
name = "tokel"
description = "A declarative, pipeline-based templating engine for simplifying Rust procedural macros."
keywords = ["proc-macro", "macro", "metaprogramming", "templating", "tokenstream"]
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]
readme = "README.md"
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokel-derive = { version = "0.2.3", path = "../tokel-derive", optional = true }
tokel-engine = { version = "0.2.3", path = "../tokel-engine", optional = true }

[features]
default = ["derive"]

derive = ["dep:tokel-derive"]
engine = ["dep:tokel-engine"]
