[package]
name = "tokel-engine"
description = "The core parsing, AST, and bottom-up evaluation engine for the Tokel macro language."
keywords = ["parsing", "ast", "evaluation", "metaprogramming", "tokel"]
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]
readme = "README.md"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
proc-macro2.workspace = true
syn.workspace = true

[dev-dependencies]
quote.workspace = true
